First task

In [ ]:
import numpy as np

A = np.random.random((10,3))
print (A)
for i in range(10):
    for j in range(3):
        if abs(A[i,j]-0.5) < minimum:
            minimum = abs(A[i,j]-0.5)
            flag = j
    print (A[i,flag])
    minimum = 1

Second Task

In [34]:
A = np.random.random((6,6))
print (A)
for i in range(6):
    print(sum(A[i])/(np.min(A, axis = 0))[i])

[[0.62015789 0.65038773 0.9114889  0.71523894 0.26042383 0.8804093 ]
 [0.45128127 0.29560608 0.67332161 0.01070507 0.39376777 0.44091757]
 [0.07392986 0.90766573 0.70128939 0.8475364  0.43598642 0.97275734]
 [0.83203037 0.35513602 0.44404284 0.10301127 0.28515448 0.4595392 ]
 [0.75348487 0.63552028 0.62471314 0.15044992 0.66734009 0.63308972]
 [0.34391779 0.89893141 0.61365807 0.35553624 0.75845574 0.27215319]]
54.620778043159255
7.664251456812929
8.871137666192036
231.5645159978672
13.303690341556345
11.914805834903765


Third Task

In [37]:
k = 0
x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])
for i in range (len (x)):
    if (x[i] > 0 and i>0 and x[i-1] == 0):
        if (x[i] > k):
            k = x[i]
print (k)

5


Fourth Task

In [39]:
x = np.ones(10)
i = np.array([0, 1, 2, 3, 5, 5, 5, 8])
for j in range(len(i)):
    x[i[j]] += 1  
print (x)

[2. 2. 2. 2. 1. 4. 1. 1. 2. 1.]


Fiveth Task will be continued 